# -*- coding: utf-8 -*-
"""ExpenceTracker App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M1hWIV18MYQNUbVCZZOKw_UOw8J47d9B
"""

!pip install streamlit pyngrok

import streamlit as st
from pyngrok import ngrok
import subprocess
import os
import sys

# Streamlit app content
streamlit_code = """
import streamlit as st

st.title('Hello from Colab with Streamlit!')
st.write('This is a simple Streamlit app running in Google Colab.')
"""

# Save the Streamlit app to a file
with open("app.py", "w") as f:
    f.write(streamlit_code)

# Authenticate ngrok
# Get your authtoken from https://dashboard.ngrok.com/get-started/your-authtoken
NGROK_AUTH_TOKEN = "355GvqNqPr4KSAap28WvBwDknUK_2bfhU1qxzF3W6eAzZ5ypX"
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# Run the Streamlit app in the background
process = subprocess.Popen([sys.executable, "-m", "streamlit", "run", "app.py"])

# Create a tunnel
public_url = ngrok.connect(8501)
print(f"Streamlit app URL: {public_url}")

# Keep the process running until interrupted
try:
    process.wait()
except KeyboardInterrupt:
    print("Streamlit app stopped.")
    ngrok.kill()

from pyngrok import ngrok
ngrok.set_auth_token("355GvqNqPr4KSAap28WvBwDknUK_2bfhU1qxzF3WeAzZ5ypX")

!streamlit run app.py &

public_url = ngrok.connect(8501)
print(" Your app is live at:", public_url)